const nodeConfig = {
  INITIAL_CUSTOM_NODE_NAME: "myNode",
  STARTING_X_POS: 0,
  STARTING_Y_POS: 0,
  NODE_VARIANT_ID_LENGTH: 5,
  NODE_ID_LENGTH: 5,
  HANDLETYPE_QUANTITY_MIN: 1,
  HANDLETYPE_QUANTITY_MAX: 20,
  COMPONENT_MODAL_FORM_CREATES_TOAST_NOTIFICATION_ON_SUBMIT_SUCCESS: true,
  COMPONENT_MODAL_FORM_CREATES_TOAST_NOTIFICATION_ON_SUBMIT_FAILURE: true,
  EDITING_VARIANT_EDITS_AFFECTED_EDGES: true,
  DELETION_REQUIRES_USER_CONFIRMATION: true,
  DELETION_DELETES_AFFECTED_EDGES: true,
  DELETION_CREATES_TOAST_NOTIFICATION: true,
  UNKNOWN_NODE_VARIANT_STRING: "unknown component type",
  UNKNOWN_VARIANT_INDEX_STRING: "unknown index",
  DEFAULT_COLOR_STRING: "gray",
};

export default nodeConfig;

export const nodeBackgroundBrightnessTailwind = {
  normal: 600,
  hover: 500,
};
